name: Crowdin Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: ['main']
    paths: ['lang/en-US.json']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  PULL_REQUEST_TITLE: 'New Crowdin translations'
  PULL_REQUEST_BODY: 'New Crowdin pull request with translations'

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin upload and download translations
        uses: crowdin/github-action@v2
        id: crowdin_update
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin_translations
          create_pull_request: true
          pull_request_title: ${{ env.PULL_REQUEST_TITLE }}
          pull_request_body: ${{ env.PULL_REQUEST_BODY }}
          pull_request_labels: "automerge"
          pull_request_base_branch_name: 'main'
          source: "lang/en-US.json"
          translation: "lang/%locale%.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Merge crowdin translations
        id: automerge
        if: steps.crowdin_update.outputs.pull_request_number
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          MERGE_METHOD: "squash"
          PULL_REQUEST: "${{ steps.crowdin_update.outputs.pull_request_number }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        